version: '3'

services:
  db: 
    container_name: ${MONGODB}
    image: mongo:6.0
    volumes:
      - poke_vol:/data/db
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: ['--auth']
  mongo-express:
    depends_on:
      - db
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGODB}

  poke-app:
    depends_on:
      - db
      - mongo-express
    image: klerith/pokemon-nest-app:1.0.0
    ports:
      - 3000:3000
    environment:
      MONGODB: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGODB}:27017
      DB_NAME: ${MONGODB}
    restart: always

volumes:
  poke_vol: 
    external: false
    